#!/usr/bin/python3
import sys


def factorize() -> None:
    try:
        file = sys.argv[1]
        with open(file) as lines:
            for line in lines:
                num = int(line.strip())
                # find the lowest  unit factor
                for i in range(2, num):
                    if num % i == 0:
                        print(f"{num}={num//i}*{i}")
                        break
    except Exception as e:
        print(e)


if __name__ == "__main__":
    factorize()
