#!/usr/bin/python3
import sys


def _is_prime(n: int) -> bool:

    if (n <= 1):
        return False
    if (n <= 3):  # 2 and 3 is prime
        return True

    if (n % 2 == 0 or n % 3 == 0):
        return False
    ind = 5
    while (ind * ind <= n):
        if n % ind == 0 or (n % (ind + 2)) == 0:
            return False
        ind += 6
    return True


def rsa() -> None:

    try:
        file = sys.argv[1]
        with open(file) as lines:
            line = lines.readline()
            num = int(line.strip())
            for i in range(3, num):
                if num % i == 0 and _is_prime(i) and _is_prime(num//i):
                    print(f"{num}={num//i}*{i}")
                    break

    except Exception as e:
        print(e)


if __name__ == "__main__":
    rsa()
